### ISSUE TITLE
 Consider chaning interrfaces to not return pointer parameters

### ISSUE THREAD

**Issue by TheHawkis** [assaabloy-ppi/dualsalt#8]
createKeyPair(out publicKey, out secretKey, random)
rotateKey(out publicKey, in/out secretKey, random, boolean)

All return data in its parameters. This is quite ugly. Suggest to change the interface to:

secretKey= createKeyPair(random) 
// Use createKeyPair() with calculatePublicKey(secretKey) to get public key
secretKeyOut = rotateKey(secretKeyIn, random, boolean)
// rotateKey() dose never need the new publicKey. Shall never be used as a single key pair except when validating m2

**Comment by franslundberg** [comment]
I like this. In addition, I would rename "createKeyPair" to "createKey" (or createSecretKey).

**Comment by TheHawkis** [comment]
Close. Not fixed!

This is a good idea and it would make a much for the API in Java. The thing is that this is not a interface optimised for Java usage but optimised for portability. That is why it has it rugged C:ish feel. DualSalts create key function try to match those original TweetNaCl create key functions. That is why it do not return a KeyPair object that would make more sense.
With this said it would make sense to wrap DualSalt in some kind of more Java specific layer. Except from having a KeyPair object it could wrap all ugly byte arrays in more specific types. Add random sources in that functions that need it. That wrapper should not be a part of this repository. We do not want to specify the random source or the types. That could be project dependent.
